const actionTypes = Object.freeze({
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE_APP: 'CHANGE_LANGUAGE',

    // handle register and login

    LOGIN_OR_REGISTER_SUCCESS: 'LOGIN_OR_REGISTER_SUCCESS',
    LOGIN_OR_REGISTER_FAILED: 'LOGIN_OR_REGISTER_FAILED',

    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
});

export default actionTypes;
